/*
 * Copyright (C) 2000-2023 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.tests.components.ui;

import com.vaadin.server.VaadinRequest;
import com.vaadin.tests.components.AbstractTestUI;

/**
 * Empty test ui to check auto-generated style name for UI.
 *
 * @author Vaadin Ltd
 */
public class UIAutoGeneratedStyleName extends AbstractTestUI {

    @Override
    protected void setup(VaadinRequest request) {
    }

    @Override
    protected String getTestDescription() {
        return "Add UI specific autogenerated style name to ui div element"
                + " and overlays container";
    }

    @Override
    protected Integer getTicketNumber() {
        return 14670;
    }

}
