/*
 * Copyright (C) 2000-2023 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.annotations;

/**
 * Marker annotation for automatically generated code elements.
 *
 * These elements may be modified or removed by code generation.
 *
 * @author Vaadin Ltd.
 * @since 6.0
 */
public @interface AutoGenerated {

}
