/*
 * Copyright (C) 2000-2023 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.client.ui.dd;

/**
 * Generated by
 * {@link com.vaadin.server.widgetsetutils.AcceptCriteriaFactoryGenerator}
 */
public abstract class VAcceptCriterionFactory {

    public abstract VAcceptCriterion get(String name);
}
